from typing import List, Dict
import random

class StockRegistry:
    """Institutional Master Registry for BIST ALL Market Coverage (V3)."""

    def __init__(self):
        # Expanded BIST Registry with Sector and Industry
        self._stocks = {
            "THYAO": {"name": "Türk Hava Yolları", "sector": "Ulaştırma", "industry": "Havayolları"},
            "ASELS": {"name": "Aselsan", "sector": "Savunma", "industry": "Elektronik Savunma"},
            "EREGL": {"name": "Erdemir", "sector": "Metal Ana", "industry": "Demir Çelik"},
            "KCHOL": {"name": "Koç Holding", "sector": "Holding", "industry": "Çok Başlı Holding"},
            "SISE": {"name": "Şişecam", "sector": "Cam ve Kimya", "industry": "Cam Sanayi"},
            "AKBNK": {"name": "Akbank", "sector": "Bankacılık", "industry": "Mevduat Bankacılığı"},
            "GARAN": {"name": "Garanti BBVA", "sector": "Bankacılık", "industry": "Mevduat Bankacılığı"},
            "TUPRS": {"name": "Tüpraş", "sector": "Petrol ve Gaz", "industry": "Petrol Rafinerisi"},
            "BIMAS": {"name": "Bim Mağazalar", "sector": "Perakende", "industry": "Gıda Perakendeciliği"},
            "SASA": {"name": "Sasa Polyester", "sector": "Kimya", "industry": "Polyester ve Fiber"},
            "TOASO": {"name": "Tofaş Oto", "sector": "Otomotiv", "industry": "Binek Araç Üretimi"},
            "FROTO": {"name": "Ford Otosan", "sector": "Otomotiv", "industry": "Ticari Araç Üretimi"},
            "ARCLK": {"name": "Arçelik", "sector": "Dayanıklı Tüketim", "industry": "Beyaz Eşya"},
            "VESTL": {"name": "Vestel", "sector": "Elektronik", "industry": "Tüketici Elektroniği"},
            "PETKM": {"name": "Petkim", "sector": "Kimya", "industry": "Petrokimya"},
            "TKFEN": {"name": "Tekfen Holding", "sector": "İnşaat", "industry": "Taahhüt ve Gübre"},
            "DOAS": {"name": "Doğuş Otomotiv", "sector": "Otomotiv", "industry": "Araç Dağıtımı"},
            "ISCTR": {"name": "İş Bankası (C)", "sector": "Bankacılık", "industry": "Mevduat Bankacılığı"},
            "YKBNK": {"name": "Yapı Kredi", "sector": "Bankacılık", "industry": "Mevduat Bankacılığı"},
            "HALKB": {"name": "Halkbank", "sector": "Bankacılık", "industry": "Kamu Bankacılığı"},
            "VAKBN": {"name": "Vakıfbank", "sector": "Bankacılık", "industry": "Kamu Bankacılığı"},
            "TSKB": {"name": "TSKB", "sector": "Bankacılık", "industry": "Yatırım Bankacılığı"},
            "KARDMD": {"name": "Kardemir (D)", "sector": "Metal Ana", "industry": "Demir Çelik"},
            "PGSUS": {"name": "Pegasus", "sector": "Ulaştırma", "industry": "Düşük Maliyetli Havayolu"},
            "ENKAI": {"name": "Enka İnşaat", "sector": "İnşaat", "industry": "Global Taahhüt"},
            "TAVHL": {"name": "TAV Havalimanları", "sector": "Ulaştırma", "industry": "Havalimanı İşletmeciliği"},
            "SOKM": {"name": "Şok Marketler", "sector": "Perakende", "industry": "Gıda Perakendeciliği"},
            "MGROS": {"name": "Migros", "sector": "Perakende", "industry": "Gıda Perakendeciliği"},
            "TTKOM": {"name": "Türk Telekom", "sector": "Telekomünikasyon", "industry": "Sabit ve Mobil Şebeke"},
            "TCELL": {"name": "Turkcell", "sector": "Telekomünikasyon", "industry": "Mobil İletişim"},
            "KOZAL": {"name": "Koza Altın", "sector": "Madencilik", "industry": "Altın Madenciliği"},
            "KOZAA": {"name": "Koza Anadolu Metal", "sector": "Madencilik", "industry": "Bakır ve Diğer Madenler"},
            "IPEKE": {"name": "İpek Doğal Enerji", "sector": "Enerji", "industry": "Petrol ve Doğal Gaz"},
            "ODAS": {"name": "Odaş Elektrik", "sector": "Enerji", "industry": "Elektrik Üretimi"},
            "AKSEN": {"name": "Aksa Enerji", "sector": "Enerji", "industry": "Elektrik Üretimi"},
            "ZOREN": {"name": "Zorlu Enerji", "sector": "Enerji", "industry": "Yenilenebilir Enerji"},
            "ALARK": {"name": "Alarko Holding", "sector": "Holding", "industry": "Enerji ve Gayrimenkul"},
            "SAHOL": {"name": "Sabancı Holding", "sector": "Holding", "industry": "Finans ve Sanayi"},
            "GUBRF": {"name": "Gübre Fabrikaları", "sector": "Kimya", "industry": "Gübre Üretimi"},
            "HEKTS": {"name": "Hektaş", "sector": "Kimya", "industry": "Tarımsal İlaç"},
            "EGEEN": {"name": "Ege Endüstri", "sector": "Otomotiv Yan", "industry": "Dingil ve Parça"},
            "OTKAR": {"name": "Otokar", "sector": "Otomotiv", "industry": "Zırhlı Araç ve Otobüs"},
            "CIMSA": {"name": "Çimsa", "sector": "Çimento", "industry": "Beyaz Çimento"},
            "AKCNS": {"name": "Akçansa", "sector": "Çimento", "industry": "Yapı Malzemeleri"},
            "OYAKC": {"name": "Oyak Çimento", "sector": "Çimento", "industry": "Yapı Malzemeleri"},
            "ULKER": {"name": "Ülker Bisküvi", "sector": "Gıda", "industry": "Atıştırmalık"},
            "BRYAT": {"name": "Borusan Yatırım", "sector": "Holding", "industry": "Yatırım Holding"},
            "BRISA": {"name": "Brisa", "sector": "Otomotiv Yan", "industry": "Lastik Üretimi"},
            "ALFAS": {"name": "Alfa Solar Enerji", "sector": "Enerji", "industry": "Güneş Paneli"},
            "ASTOR": {"name": "Astor Enerji", "sector": "Enerji", "industry": "Transformatör Üretimi"},
            "KONTR": {"name": "Kontrolmatik", "sector": "Teknoloji", "industry": "Enerji Depolama"},
            "SMRTG": {"name": "Smart Güneş Enerjisi", "sector": "Enerji", "industry": "Güneş Enerjisi"},
            "YEOTK": {"name": "Yeo Teknoloji", "sector": "Teknoloji", "industry": "Otomasyon"},
            "MIATK": {"name": "Mia Teknoloji", "sector": "Teknoloji", "industry": "Yazılım Çözümleri"},
            "EUPWR": {"name": "Europower Enerji", "sector": "Enerji", "industry": "Elektrik Ekipmanları"},
            "CWENE": {"name": "CW Enerji", "sector": "Enerji", "industry": "Güneş Paneli"},
            "KAYSE": {"name": "Kayseri Şeker", "sector": "Gıda", "industry": "Şeker Üretimi"},
            "TATGD": {"name": "Tat Gıda", "sector": "Gıda", "industry": "Konserve ve Salça"},
            "YYLGD": {"name": "Yayla Gıda", "sector": "Gıda", "industry": "Bakliyat"},
            "CCOLA": {"name": "Coca-Cola İçecek", "sector": "Gıda ve İçecek", "industry": "Meşrubat"},
            "AEFES": {"name": "Anadolu Efes", "sector": "Gıda ve İçecek", "industry": "Bira ve Malt"},
            "DOHOL": {"name": "Doğan Holding", "sector": "Holding", "industry": "Çok Başlı Holding"},
            "SKBNK": {"name": "Şekerbank", "sector": "Bankacılık", "industry": "Mevduat Bankacılığı"},
            "ALBRK": {"name": "Albaraka Türk", "sector": "Bankacılık", "industry": "Katılım Bankacılığı"},
            "QNBFB": {"name": "QNB Finansbank", "sector": "Bankacılık", "industry": "Mevduat Bankacılığı"},
            "TURSG": {"name": "Türkiye Sigorta", "sector": "Sigorta", "industry": "Hayat Dışı Sigorta"},
            "ANSGR": {"name": "Anadolu Sigorta", "sector": "Sigorta", "industry": "Hayat Dışı Sigorta"},
            "AKGRT": {"name": "Aksigorta", "sector": "Sigorta", "industry": "Elementer Sigorta"},
            "RAYYS": {"name": "Reysaş Lojistik", "sector": "Ulaştırma", "industry": "Lojistik Hizmetleri"},
            "EKGYO": {"name": "Emlak Konut GYO", "sector": "Gayrimenkul", "industry": "GYO"},
            "TRGYO": {"name": "Torunlar GYO", "sector": "Gayrimenkul", "industry": "GYO"},
            "SNGYO": {"name": "Sinpaş GYO", "sector": "Gayrimenkul", "industry": "GYO"},
            "OZKGY": {"name": "Özak GYO", "sector": "Gayrimenkul", "industry": "GYO"},
            "ASUZU": {"name": "Anadolu Isuzu", "sector": "Otomotiv", "industry": "Ticari Araç"},
            "KARSN": {"name": "Karsan", "sector": "Otomotiv", "industry": "Ticari Araç"},
            "AGHOL": {"name": "Anadolu Grubu", "sector": "Holding", "industry": "İçecek ve Perakende"},
            "KORDS": {"name": "Kordsa", "sector": "Tekstil ve Kimya", "industry": "Lastik Güçlendirme"},
            "AKSA": {"name": "Aksa Akrilik", "sector": "Kimya", "industry": "Akrilik Elyaf"},
            "LOGO": {"name": "Logo Yazılım", "sector": "Teknoloji", "industry": "Kurumsal Yazılım"},
            "ALCTL": {"name": "Alcatel Lucent", "sector": "Teknoloji", "industry": "Telekom Ekipmanları"},
            "NETAS": {"name": "Netaş", "sector": "Teknoloji", "industry": "Bilişim Çözümleri"},
            "PENTA": {"name": "Penta Teknoloji", "sector": "Bilişim", "industry": "Bilgisayar Dağıtımı"},
            "INDES": {"name": "Indeks Bilgisayar", "sector": "Bilişim", "industry": "Teknoloji Dağıtımı"},
            "ARENA": {"name": "Arena Bilgisayar", "sector": "Bilişim", "industry": "Teknoloji Dağıtımı"},
            "DESPC": {"name": "Despec Bilgisayar", "sector": "Bilişim", "industry": "Sarf Malzemesi Dağıtımı"},
            "VAKKO": {"name": "Vakko Tekstil", "sector": "Tekstil", "industry": "Lüks Giyim"},
            "MAVI": {"name": "Mavi Giyim", "sector": "Tekstil", "industry": "Hazır Giyim"},
            "TEKFK": {"name": "Tek-Art Turizm", "sector": "Turizm", "industry": "Otel İşletmeciliği"},
            "AYGAZ": {"name": "Aygaz", "sector": "Enerji", "industry": "LPG Dağıtımı"},
            "IZMDC": {"name": "İzmir Demir Çelik", "sector": "Metal Ana", "industry": "Demir Çelik Çubuk"},
            "KARTN": {"name": "Kartonsan", "sector": "Kağıt", "industry": "Karton Üretimi"},
            "BAGFS": {"name": "Bagfaş", "sector": "Kimya", "industry": "Gübre"},
            "EGEGU": {"name": "Ege Gübre", "sector": "Kimya", "industry": "Gübre ve Liman"},
            "BANVT": {"name": "Banvit", "sector": "Gıda", "industry": "Beyaz Et"},
            "GOLTS": {"name": "Göltaş Çimento", "sector": "Çimento", "industry": "İnşaat Malzemeleri"},
            "AFYON": {"name": "Afyon Çimento", "sector": "Çimento", "industry": "İnşaat Malzemeleri"},
            "NUHCM": {"name": "Nuh Çimento", "sector": "Çimento", "industry": "İnşaat Malzemeleri"},
            "PARSN": {"name": "Parsan", "sector": "Otomotiv Yan", "industry": "Dövme Çelik"},
            "GOODY": {"name": "Good-Year", "sector": "Otomotiv Yan", "industry": "Lastik"},
            "TMSN": {"name": "Tümosan", "sector": "Otomotiv", "industry": "Traktör Üretimi"},
            "VESBE": {"name": "Vestel Beyaz Eşya", "sector": "Dayanıklı Tüketim", "industry": "Ev Aletleri"},
            "DOCO": {"name": "DO & CO", "sector": "Ulaştırma", "industry": "İkram Hizmetleri"},
            "CLEBI": {"name": "Çelebi", "sector": "Ulaştırma", "industry": "Yer Hizmetleri"},
            "RHEAG": {"name": "Rhea Girişim", "sector": "Finansal", "industry": "Girişim Sermayesi"},
            "GOZDE": {"name": "Gözde Girişim", "sector": "Finansal", "industry": "Girişim Sermayesi"},
            "VERTU": {"name": "Verusaturk Girişim", "sector": "Finansal", "industry": "Girişim Sermayesi"},
            "INVEO": {"name": "Inveo Yatırım", "sector": "Holding", "industry": "Sermaye Piyasası"},
            "GLYHO": {"name": "Global Yatırım", "sector": "Holding", "industry": "Liman ve Enerji"},
            "POLHO": {"name": "Polisan Holding", "sector": "Holding", "industry": "Boya ve Kimya"},
            "ECILC": {"name": "Eczacıbaşı İlaç", "sector": "İlaç", "industry": "İlaç Üretimi"},
            "TRILC": {"name": "Turk Ilaç Serum", "sector": "İlaç", "industry": "Serum ve Aşı"},
            "GENIL": {"name": "Gen İlaç", "sector": "İlaç", "industry": "İlaç Üretimi"},
            "RTALB": {"name": "RTA Laboratuvarları", "sector": "İlaç", "industry": "Biyoteknoloji"},
            "ANGEN": {"name": "Anatolia Tanı", "sector": "İlaç", "industry": "Biyoteknoloji"},
            "MPARK": {"name": "Medical Park", "sector": "Sağlık", "industry": "Hastane İşletmeciliği"},
            "LKMNH": {"name": "Lokman Hekim", "sector": "Sağlık", "industry": "Hastane İşletmeciliği"},
            "ISDMR": {"name": "İskenderun Demir Çelik", "sector": "Metal Ana", "industry": "Yassı Çelik"},
            "CEMAS": {"name": "Çemaş Döküm", "sector": "Metal Ana", "industry": "Döküm Sanayi"},
            "DMSAS": {"name": "Demisaş Döküm", "sector": "Metal Ana", "industry": "Döküm Sanayi"},
            "ENJSA": {"name": "Enerjisa", "sector": "Enerji", "industry": "Elektrik Dağıtımı"},
            "GWIND": {"name": "Galata Wind", "sector": "Enerji", "industry": "Rüzgar Enerjisi"},
            "BIOEN": {"name": "Biotrend Enerji", "sector": "Enerji", "industry": "Biyokütle Enerjisi"},
            "HUNER": {"name": "Hun Enerji", "sector": "Enerji", "industry": "Yenilenebilir Enerji"},
            "AENER": {"name": "Aras Enerji", "sector": "Enerji", "industry": "Enerji Dağıtımı"},
            "CANTE": {"name": "Çan2 Termik", "sector": "Enerji", "industry": "Kömür Santrali"},
            "SDTTR": {"name": "SDT Savunma", "sector": "Savunma", "industry": "Savunma Teknolojileri"},
            "TABGD": {"name": "Tab Gıda", "sector": "Gıda ve İçecek", "industry": "Fast Food"},
            "EBEBK": {"name": "Ebebek", "sector": "Perakende", "industry": "Bebek Ürünleri"},
            "HRKET": {"name": "Hareket Lojistik", "sector": "Ulaştırma", "industry": "Ağır Nakliyat"},
            "AGROT": {"name": "Agrotech", "sector": "Teknoloji", "industry": "Yazılım ve Donanım"},
            "BORSK": {"name": "Borsan Kablo", "sector": "Sanayi", "industry": "Kablo Üretimi"},
            "LMKDC": {"name": "Limak Çimento", "sector": "Çimento", "industry": "İnşaat Malzemeleri"},
            "MOGAN": {"name": "Mogan Enerji", "sector": "Enerji", "industry": "Yenilenebilir Enerji"},
            "ENTRA": {"name": "IC Enterra", "sector": "Enerji", "industry": "Yenilenebilir Enerji"},
            "KOTON": {"name": "Koton Mağazacılık", "sector": "Perakende", "industry": "Tekstil Perakende"},
            "ALTNY": {"name": "Altınay Savunma", "sector": "Savunma", "industry": "Savunma Sanayi"},
            "ODINE": {"name": "Odin Teknoloji", "sector": "Teknoloji", "industry": "Bilişim ve Telekom"},
            "ALVVM": {"name": "Alves Kablo", "sector": "Sanayi", "industry": "Enerji Kabloları"},
            "ARTMS": {"name": "Artemis Halı", "sector": "Tekstil", "industry": "Ev Tekstili"},
            "OBA": {"name": "Oba Makarnacılık", "sector": "Gıda", "industry": "Unlu Mamuller"},
        }
        # This list covers major BIST ALL stocks including 2024 IPOs.
        # Total approx 150 symbols here, in a real environment it's 600+.

    def get_all_symbols(self) -> List[str]:
        """Returns randomized symbols to eliminate bias (V3)."""
        symbols = list(set(self._stocks.keys()))
        random.shuffle(symbols)
        return symbols

    def get_stock_data(self, symbol: str) -> Dict:
        """Returns stock metadata with V3 institutional fallback."""
        return self._stocks.get(symbol, {"name": f"{symbol} Stock", "sector": "Genel", "industry": "Genel"})

stock_registry = StockRegistry()
