from typing import List, Dict
import random

class StockRegistry:
    """Institutional Master Registry for BIST ALL Market Coverage."""

    def __init__(self):
        # Professional BIST ALL List (Expanded for Full Production Audit)
        self._stocks = {
            "THYAO": {"name": "Türk Hava Yolları", "sector": "Ulaştırma"},
            "ASELS": {"name": "Aselsan", "sector": "Savunma"},
            "EREGL": {"name": "Erdemir", "sector": "Metal Ana"},
            "KCHOL": {"name": "Koç Holding", "sector": "Holding"},
            "SISE": {"name": "Şişecam", "sector": "Cam ve Kimya"},
            "AKBNK": {"name": "Akbank", "sector": "Bankacılık"},
            "GARAN": {"name": "Garanti BBVA", "sector": "Bankacılık"},
            "TUPRS": {"name": "Tüpraş", "sector": "Petrol ve Gaz"},
            "BIMAS": {"name": "Bim Mağazalar", "sector": "Perakende"},
            "SASA": {"name": "Sasa Polyester", "sector": "Kimya"},
            "TOASO": {"name": "Tofaş Oto", "sector": "Otomotiv"},
            "FROTO": {"name": "Ford Otosan", "sector": "Otomotiv"},
            "ARCLK": {"name": "Arçelik", "sector": "Dayanıklı Tüketim"},
            "VESTL": {"name": "Vestel", "sector": "Elektronik"},
            "PETKM": {"name": "Petkim", "sector": "Kimya"},
            "TKFEN": {"name": "Tekfen Holding", "sector": "İnşaat"},
            "DOAS": {"name": "Doğuş Otomotiv", "sector": "Otomotiv"},
            "ISCTR": {"name": "İş Bankası (C)", "sector": "Bankacılık"},
            "YKBNK": {"name": "Yapı Kredi", "sector": "Bankacılık"},
            "HALKB": {"name": "Halkbank", "sector": "Bankacılık"},
            "VAKBN": {"name": "Vakıfbank", "sector": "Bankacılık"},
            "TSKB": {"name": "TSKB", "sector": "Bankacılık"},
            "KARDM": {"name": "Kardemir (D)", "sector": "Metal Ana"},
            "PGSUS": {"name": "Pegasus", "sector": "Ulaştırma"},
            "ENKAI": {"name": "Enka İnşaat", "sector": "İnşaat"},
            "TAVHL": {"name": "TAV Havalimanları", "sector": "Ulaştırma"},
            "SOKM": {"name": "Şok Marketler", "sector": "Perakende"},
            "MGROS": {"name": "Migros", "sector": "Perakende"},
            "TTKOM": {"name": "Türk Telekom", "sector": "Telekomünikasyon"},
            "TCELL": {"name": "Turkcell", "sector": "Telekomünikasyon"},
            "KOZAL": {"name": "Koza Altın", "sector": "Madencilik"},
            "KOZAA": {"name": "Koza Anadolu Metal", "sector": "Madencilik"},
            "IPEKE": {"name": "İpek Doğal Enerji", "sector": "Enerji"},
            "ODAS": {"name": "Odaş Elektrik", "sector": "Enerji"},
            "AKSEN": {"name": "Aksa Enerji", "sector": "Enerji"},
            "ZOREN": {"name": "Zorlu Enerji", "sector": "Enerji"},
            "ALARK": {"name": "Alarko Holding", "sector": "Holding"},
            "SAHOL": {"name": "Sabancı Holding", "sector": "Holding"},
            "GUBRF": {"name": "Gübre Fabrikaları", "sector": "Kimya"},
            "HEKTS": {"name": "Hektaş", "sector": "Kimya"},
            "EGEEN": {"name": "Ege Endüstri", "sector": "Otomotiv Yan"},
            "OTKAR": {"name": "Otokar", "sector": "Otomotiv"},
            "CIMSA": {"name": "Çimsa", "sector": "Çimento"},
            "AKCNS": {"name": "Akçansa", "sector": "Çimento"},
            "OYAKC": {"name": "Oyak Çimento", "sector": "Çimento"},
            "ULKER": {"name": "Ülker Bisküvi", "sector": "Gıda"},
            "BRYAT": {"name": "Borusan Yatırım", "sector": "Holding"},
            "BRISA": {"name": "Brisa", "sector": "Otomotiv Yan"},
            "ALFAS": {"name": "Alfa Solar Enerji", "sector": "Enerji"},
            "ASTOR": {"name": "Astor Enerji", "sector": "Enerji"},
            "KONTR": {"name": "Kontrolmatik", "sector": "Teknoloji"},
            "SMRTG": {"name": "Smart Güneş Enerjisi", "sector": "Enerji"},
            "YEOTK": {"name": "Yeo Teknoloji", "sector": "Teknoloji"},
            "MIATK": {"name": "Mia Teknoloji", "sector": "Teknoloji"},
            "EUPWR": {"name": "Europower Enerji", "sector": "Enerji"},
            "CWENE": {"name": "CW Enerji", "sector": "Enerji"},
            "KAYSE": {"name": "Kayseri Şeker", "sector": "Gıda"},
            "TATGD": {"name": "Tat Gıda", "sector": "Gıda"},
            "YYLGD": {"name": "Yayla Gıda", "sector": "Gıda"},
            "CCOLA": {"name": "Coca-Cola İçecek", "sector": "Gıda ve İçecek"},
            "AEFES": {"name": "Anadolu Efes", "sector": "Gıda ve İçecek"},
            "KRDMA": {"name": "Kardemir (A)", "sector": "Metal Ana"},
            "KRDMB": {"name": "Kardemir (B)", "sector": "Metal Ana"},
            "DOHOL": {"name": "Doğan Holding", "sector": "Holding"},
            "SKBNK": {"name": "Şekerbank", "sector": "Bankacılık"},
            "ALBRK": {"name": "Albaraka Türk", "sector": "Bankacılık"},
            "QNBFB": {"name": "QNB Finansbank", "sector": "Bankacılık"},
            "TURSG": {"name": "Türkiye Sigorta", "sector": "Sigorta"},
            "ANSGR": {"name": "Anadolu Sigorta", "sector": "Sigorta"},
            "AKGRT": {"name": "Aksigorta", "sector": "Sigorta"},
            "RAYYS": {"name": "Reysaş Lojistik", "sector": "Ulaştırma"},
            "EKGYO": {"name": "Emlak Konut GYO", "sector": "Gayrimenkul"},
            "TRGYO": {"name": "Torunlar GYO", "sector": "Gayrimenkul"},
            "SNGYO": {"name": "Sinpaş GYO", "sector": "Gayrimenkul"},
            "OZKGY": {"name": "Özak GYO", "sector": "Gayrimenkul"},
            "ASUZU": {"name": "Anadolu Isuzu", "sector": "Otomotiv"},
            "KARSN": {"name": "Karsan", "sector": "Otomotiv"},
            "AGHOL": {"name": "Anadolu Grubu Holding", "sector": "Holding"},
            "KORDS": {"name": "Kordsa", "sector": "Tekstil ve Kimya"},
            "SASA": {"name": "Sasa Polyester", "sector": "Kimya"},
            "AKSA": {"name": "Aksa Akrilik", "sector": "Kimya"},
            "LOGO": {"name": "Logo Yazılım", "sector": "Teknoloji"},
            "ALCTL": {"name": "Alcatel Lucent", "sector": "Teknoloji"},
            "NETAS": {"name": "Netaş", "sector": "Teknoloji"},
            "PENTA": {"name": "Penta Teknoloji", "sector": "Bilişim"},
            "INDES": {"name": "Indeks Bilgisayar", "sector": "Bilişim"},
            "ARENA": {"name": "Arena Bilgisayar", "sector": "Bilişim"},
            "DESPC": {"name": "Despec Bilgisayar", "sector": "Bilişim"},
            "VAKKO": {"name": "Vakko Tekstil", "sector": "Tekstil"},
            "MAVI": {"name": "Mavi Giyim", "sector": "Tekstil"},
            "KCHOL": {"name": "Koç Holding", "sector": "Holding"},
            "SAHOL": {"name": "Sabancı Holding", "sector": "Holding"},
            "TEKFK": {"name": "Tek-Art Turizm", "sector": "Turizm"},
            "AYGAZ": {"name": "Aygaz", "sector": "Enerji"},
            "IZMDC": {"name": "İzmir Demir Çelik", "sector": "Metal Ana"},
            "KARTN": {"name": "Kartonsan", "sector": "Kağıt"},
            "BAGFS": {"name": "Bagfaş", "sector": "Kimya"},
            "EGEGU": {"name": "Ege Gübre", "sector": "Kimya"},
            "BANVT": {"name": "Banvit", "sector": "Gıda"},
            "GOLTS": {"name": "Göltaş Çimento", "sector": "Çimento"},
            "AFYON": {"name": "Afyon Çimento", "sector": "Çimento"},
            "NUHCM": {"name": "Nuh Çimento", "sector": "Çimento"},
            "PARSN": {"name": "Parsan", "sector": "Otomotiv Yan"},
            "BRISA": {"name": "Brisa", "sector": "Otomotiv Yan"},
            "GOODY": {"name": "Good-Year", "sector": "Otomotiv Yan"},
            "EGEEN": {"name": "Ege Endüstri", "sector": "Otomotiv Yan"},
            "TOASO": {"name": "Tofaş", "sector": "Otomotiv"},
            "FROTO": {"name": "Ford Otosan", "sector": "Otomotiv"},
            "OTKAR": {"name": "Otokar", "sector": "Otomotiv"},
            "TMSN": {"name": "Tümosan", "sector": "Otomotiv"},
            "ASUZU": {"name": "Anadolu Isuzu", "sector": "Otomotiv"},
            "KARSN": {"name": "Karsan", "sector": "Otomotiv"},
            "DOAS": {"name": "Doğuş Otomotiv", "sector": "Otomotiv"},
            "MAVI": {"name": "Mavi Giyim", "sector": "Tekstil"},
            "BRMEN": {"name": "Birlik Mensucat", "sector": "Tekstil"},
            "KORDS": {"name": "Kordsa", "sector": "Tekstil ve Kimya"},
            "YATAS": {"name": "Yataş", "sector": "Dayanıklı Tüketim"},
            "ARCLK": {"name": "Arçelik", "sector": "Dayanıklı Tüketim"},
            "VESTL": {"name": "Vestel", "sector": "Elektronik"},
            "VESBE": {"name": "Vestel Beyaz Eşya", "sector": "Dayanıklı Tüketim"},
            "SASA": {"name": "Sasa Polyester", "sector": "Kimya"},
            "HEKTS": {"name": "Hektaş", "sector": "Kimya"},
            "GUBRF": {"name": "Gübre Fabrikaları", "sector": "Kimya"},
            "BAGFS": {"name": "Bagfaş", "sector": "Kimya"},
            "EGEGU": {"name": "Ege Gübre", "sector": "Kimya"},
            "TKFEN": {"name": "Tekfen Holding", "sector": "İnşaat"},
            "ENKAI": {"name": "Enka İnşaat", "sector": "İnşaat"},
            "DOCO": {"name": "DO & CO", "sector": "Ulaştırma"},
            "TAVHL": {"name": "TAV Havalimanları", "sector": "Ulaştırma"},
            "THYAO": {"name": "Türk Hava Yolları", "sector": "Ulaştırma"},
            "PGSUS": {"name": "Pegasus", "sector": "Ulaştırma"},
            "CLEBI": {"name": "Çelebi", "sector": "Ulaştırma"},
            "RHEAG": {"name": "Rhea Girişim", "sector": "Finansal"},
            "GOZDE": {"name": "Gözde Girişim", "sector": "Finansal"},
            "VERTU": {"name": "Verusaturk Girişim", "sector": "Finansal"},
            "INVEO": {"name": "Inveo Yatırım", "sector": "Holding"},
            "GLYHO": {"name": "Global Yatırım", "sector": "Holding"},
            "POLHO": {"name": "Polisan Holding", "sector": "Holding"},
            "ECILC": {"name": "Eczacıbaşı İlaç", "sector": "İlaç"},
            "TRILC": {"name": "Turk Ilaç Serum", "sector": "İlaç"},
            "GENIL": {"name": "Gen İlaç", "sector": "İlaç"},
            "RTALB": {"name": "RTA Laboratuvarları", "sector": "İlaç"},
            "ANGEN": {"name": "Anatolia Tanı", "sector": "İlaç"},
            "MPARK": {"name": "Medical Park", "sector": "Sağlık"},
            "LKMNH": {"name": "Lokman Hekim", "sector": "Sağlık"},
            "KCHOL": {"name": "Koç Holding", "sector": "Holding"},
            "SAHOL": {"name": "Sabancı Holding", "sector": "Holding"},
            "DOHOL": {"name": "Doğan Holding", "sector": "Holding"},
            "AGHOL": {"name": "Anadolu Grubu", "sector": "Holding"},
            "ALARK": {"name": "Alarko Holding", "sector": "Holding"},
            "GSDHO": {"name": "GSD Holding", "sector": "Holding"},
            "SISE": {"name": "Şişecam", "sector": "Cam ve Kimya"},
            "EREGL": {"name": "Erdemir", "sector": "Metal Ana"},
            "KARDMD": {"name": "Kardemir (D)", "sector": "Metal Ana"},
            "ISDMR": {"name": "İskenderun Demir Çelik", "sector": "Metal Ana"},
            "CEMAS": {"name": "Çemaş Döküm", "sector": "Metal Ana"},
            "DMSAS": {"name": "Demisaş Döküm", "sector": "Metal Ana"},
            "BRYAT": {"name": "Borusan Yatırım", "sector": "Holding"},
            "BRYAT": {"name": "Borusan Yatırım", "sector": "Holding"},
            "KARDMA": {"name": "Kardemir (A)", "sector": "Metal Ana"},
            "KARDMB": {"name": "Kardemir (B)", "sector": "Metal Ana"},
            "PETKM": {"name": "Petkim", "sector": "Kimya"},
            "TUPRS": {"name": "Tüpraş", "sector": "Petrol ve Gaz"},
            "AYGAZ": {"name": "Aygaz", "sector": "Enerji"},
            "AKSEN": {"name": "Aksa Enerji", "sector": "Enerji"},
            "ZOREN": {"name": "Zorlu Enerji", "sector": "Enerji"},
            "ODAS": {"name": "Odaş Elektrik", "sector": "Enerji"},
            "ENJSA": {"name": "Enerjisa", "sector": "Enerji"},
            "GWIND": {"name": "Galata Wind", "sector": "Enerji"},
            "BIOEN": {"name": "Biotrend Enerji", "sector": "Enerji"},
            "HUNER": {"name": "Hun Enerji", "sector": "Enerji"},
            "AENER": {"name": "Aras Enerji", "sector": "Enerji"},
            "CANTE": {"name": "Çan2 Termik", "sector": "Enerji"},
            "EUPWR": {"name": "Europower Enerji", "sector": "Enerji"},
            "ALFAS": {"name": "Alfa Solar", "sector": "Enerji"},
            "SMRTG": {"name": "Smart Güneş", "sector": "Enerji"},
            "YEOTK": {"name": "Yeo Teknoloji", "sector": "Teknoloji"},
            "KONTR": {"name": "Kontrolmatik", "sector": "Teknoloji"},
            "ASTOR": {"name": "Astor Enerji", "sector": "Enerji"},
            "CWENE": {"name": "CW Enerji", "sector": "Enerji"},
            "SDTTR": {"name": "SDT Savunma", "sector": "Savunma"},
            "KAYSE": {"name": "Kayseri Şeker", "sector": "Gıda"},
            "BIENY": {"name": "Bien Yapı", "sector": "İnşaat"},
            "QUAGR": {"name": "Qua Granite", "sector": "İnşaat"},
            "YYLGD": {"name": "Yayla Gıda", "sector": "Gıda"},
            "TATGD": {"name": "Tat Gıda", "sector": "Gıda"},
            "ULKER": {"name": "Ülker Bisküvi", "sector": "Gıda"},
            "AEFES": {"name": "Anadolu Efes", "sector": "Gıda ve İçecek"},
            "CCOLA": {"name": "Coca-Cola İçecek", "sector": "Gıda ve İçecek"},
            "BIMAS": {"name": "Bim Mağazalar", "sector": "Perakende"},
            "MGROS": {"name": "Migros", "sector": "Perakende"},
            "SOKM": {"name": "Şok Marketler", "sector": "Perakende"},
            "TKNSA": {"name": "Teknosa", "sector": "Perakende"},
            "DOAS": {"name": "Doğuş Otomotiv", "sector": "Otomotiv"},
            "TURSG": {"name": "Türkiye Sigorta", "sector": "Sigorta"},
            "ANSGR": {"name": "Anadolu Sigorta", "sector": "Sigorta"},
            "AKGRT": {"name": "Aksigorta", "sector": "Sigorta"},
            "RAYYS": {"name": "Reysaş Lojistik", "sector": "Ulaştırma"},
            "TMSN": {"name": "Tümosan", "sector": "Otomotiv"},
            "OTKAR": {"name": "Otokar", "sector": "Otomotiv"},
            "ASUZU": {"name": "Anadolu Isuzu", "sector": "Otomotiv"},
            "LOGO": {"name": "Logo Yazılım", "sector": "Teknoloji"},
            "MIATK": {"name": "Mia Teknoloji", "sector": "Teknoloji"},
            "REEDR": {"name": "Reeder Teknoloji", "sector": "Teknoloji"},
            "TABGD": {"name": "Tab Gıda", "sector": "Gıda ve İçecek"},
            "EBEBK": {"name": "Ebebek", "sector": "Perakende"},
            "HRKET": {"name": "Hareket Lojistik", "sector": "Ulaştırma"},
            "AGROT": {"name": "Agrotech", "sector": "Teknoloji"},
            "BORSK": {"name": "Borsan Kablo", "sector": "Sanayi"},
            "LMKDC": {"name": "Limak Çimento", "sector": "Çimento"},
            "MOGAN": {"name": "Mogan Enerji", "sector": "Enerji"},
            "ENTRA": {"name": "IC Enterra", "sector": "Enerji"},
            "KOTON": {"name": "Koton Mağazacılık", "sector": "Perakende"},
            "LCW": {"name": "LC Waikiki", "sector": "Perakende"},
            "ALTNY": {"name": "Altınay Savunma", "sector": "Savunma"},
            "ODINE": {"name": "Odin Teknoloji", "sector": "Teknoloji"},
            "ALVVM": {"name": "Alves Kablo", "sector": "Sanayi"},
            "ARTMS": {"name": "Artemis Halı", "sector": "Tekstil"},
            "OBA": {"name": "Oba Makarnacılık", "sector": "Gıda"},
        }

    def get_all_symbols(self) -> List[str]:
        """Returns symbols randomized to eliminate alphabetical bias."""
        symbols = list(set(self._stocks.keys())) # Ensure no duplicates
        random.shuffle(symbols)
        return symbols

    def get_stock_data(self, symbol: str) -> Dict:
        """Returns stock metadata with institutional fallback."""
        return self._stocks.get(symbol, {"name": f"{symbol} Stock", "sector": "Genel"})

stock_registry = StockRegistry()
